AllCops:
  Exclude:
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/yarn'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/LineLength:
  Enabled: false
